/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.DriverManager;
import com.mysql.jdbc.Statement;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form selection
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setText("MENU");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Frizzed BRK", 1, 14))); // NOI18N
        jTabbedPane1.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jRadioButton1.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton1.setText("ALOO WcBURGER");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel2.setText("ITEMS");

        jLabel3.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel3.setText("PRICE");

        jRadioButton2.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton2.setText("WcVEGGIIE ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton3.setText("MAHARAJA WAC");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton4.setText("SPICY PANEER WcBURGER");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton5.setText("SPICY PANEER WRAP");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton6.setText("ALOO WRAP");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel4.setText("QUANTITY");

        jTextField1.setEnabled(false);

        jTextField3.setEnabled(false);

        jTextField4.setEnabled(false);

        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel5.setText("30/-");

        jLabel6.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel6.setText("60/-");

        jLabel7.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel7.setText("85/-");

        jLabel8.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel8.setText("110/-");

        jLabel9.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel9.setText("90/-");

        jLabel10.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel10.setText("75/-");

        jTextField5.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton6)
                            .addComponent(jLabel10))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("VEG", jPanel1);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel11.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel11.setText("ITEMS");

        jLabel12.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel12.setText("QUANTITY");

        jLabel13.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel13.setText("PRICE");

        jLabel14.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel14.setText("45/-");

        jLabel15.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel15.setText("65/-");

        jLabel16.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel16.setText("90/-");

        jLabel17.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel17.setText("120/-");

        jLabel18.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel18.setText("85/-");

        jLabel19.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel19.setText("100/-");

        jRadioButton7.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton7.setText("CHICKEN WcBURGER");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton8.setText("GRILL CHICKEN WcBURGER");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton9.setText("MAHARAJA WAC");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jRadioButton10.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton10.setText("SPICY CHICKEN WcBURGER");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jRadioButton11.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton11.setText("CHICKEN WRAP");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jRadioButton12.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton12.setText("MUTTON WRAP");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        jTextField8.setEnabled(false);

        jTextField9.setEnabled(false);

        jTextField10.setEnabled(false);

        jTextField11.setEnabled(false);

        jTextField12.setEnabled(false);

        jTextField13.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18))))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jRadioButton7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jRadioButton8)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jRadioButton9)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jRadioButton10)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jRadioButton11)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jRadioButton12)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NON-VEG", jPanel2);

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel20.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel20.setText("ITEMS");

        jLabel21.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel21.setText("QUANTITY");

        jLabel22.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel22.setText("PRICE");

        jLabel23.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel23.setText("25/-");

        jLabel24.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel24.setText("55/-");

        jLabel25.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel25.setText("60/-");

        jLabel26.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel26.setText("70/-");

        jLabel27.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel27.setText("80/-");

        jLabel28.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel28.setText("60/-");

        jRadioButton13.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton13.setText("WcPUFF");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        jRadioButton14.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton14.setText("CHICKEN NUGGETS");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        jRadioButton15.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton15.setText("CHICKEN POPCORN (6 PIECES)");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        jRadioButton16.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton16.setText("FRENCH FRIES");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        jRadioButton17.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton17.setText("CHICKEN FRENCH FRIES");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        jRadioButton18.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton18.setText("VEG GRILLED SANDWICH");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        jTextField14.setEnabled(false);

        jTextField15.setEnabled(false);

        jTextField16.setEnabled(false);

        jTextField17.setEnabled(false);

        jTextField18.setEnabled(false);

        jTextField19.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton18)
                            .addComponent(jRadioButton17)
                            .addComponent(jRadioButton16)
                            .addComponent(jRadioButton15)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton14))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(67, 67, 67))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addGap(81, 81, 81))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jRadioButton13)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jRadioButton14)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jRadioButton15)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jRadioButton16)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jRadioButton17)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jRadioButton18)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SIDES", jPanel3);

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel29.setText("ITEM");

        jLabel30.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel30.setText("QUANTITY");

        jLabel31.setFont(new java.awt.Font("Kickflip BRK", 1, 18)); // NOI18N
        jLabel31.setText("PRICE");

        jLabel32.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel32.setText("35/-");

        jLabel33.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel33.setText("40/-");

        jLabel34.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel34.setText("50/-");

        jLabel35.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel35.setText("40/-");

        jLabel36.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel36.setText("30/-");

        jLabel37.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jLabel37.setText("50/-");

        jRadioButton19.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton19.setText("ICE TEA");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        jRadioButton20.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton20.setText("BLACK TEA");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        jRadioButton21.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton21.setText("COLD COFFEE");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        jRadioButton22.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton22.setText("HOT TEA");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });

        jRadioButton23.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton23.setText("DRINKING WATER");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        jRadioButton24.setFont(new java.awt.Font("Conduit 2 BRK", 1, 14)); // NOI18N
        jRadioButton24.setText("COKE/FANTA/SPRITE");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });

        jTextField20.setEnabled(false);

        jTextField21.setEnabled(false);

        jTextField22.setEnabled(false);

        jTextField23.setEnabled(false);

        jTextField24.setEnabled(false);

        jTextField25.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel31))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton19)
                            .addComponent(jRadioButton20)
                            .addComponent(jRadioButton21)
                            .addComponent(jRadioButton22)
                            .addComponent(jRadioButton23)
                            .addComponent(jRadioButton24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField25, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jTextField24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField20, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(71, 71, 71))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jRadioButton19)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jRadioButton20)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jRadioButton21)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jRadioButton22)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jRadioButton23)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jRadioButton24)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BEVERAGES", jPanel4);

        jButton1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        jButton1.setText("ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("CLEAR CART");
        jMenu1.setFont(new java.awt.Font("8-bit Limit R BRK", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("EXIT");
        jMenu2.setFont(new java.awt.Font("8-bit Limit R BRK", 1, 18)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(268, 268, 268))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(287, 287, 287))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String item1 = null,item2 = null,item3 = null,item4 = null,item5 = null,item6 = null,item7 = null,item8 = null
        ,item9 = null,item10 = null,item11 = null,item12 = null,item13 = null,item14 = null,item15 = null
        ,item16 = null,item17 = null,item18 = null,item19 = null,item20 = null,item21 = null,item22 = null
        ,item23 = null,item24 = null,indicate,user = null;
int qty1 = 0,qty2= 0,qty3= 0,qty4= 0,qty5= 0,qty6= 0,qty7= 0,qty8= 0,qty9= 0,qty10= 0,qty11= 0,qty12= 0,qty13= 0
        ,qty14= 0,qty15= 0,qty16= 0,qty17= 0,qty18= 0,qty19= 0,qty20= 0,qty21= 0,qty22= 0,qty23= 0
        ,qty24= 0,price = 0;      
int price1 = 0,price3= 0,price2= 0,price4= 0,price5= 0,price6= 0,price7= 0,price8= 0,price9= 0,price10= 0
        ,price11= 0,price12= 0,price13= 0,price14= 0,price15= 0,price16= 0,price17= 0,price18= 0,price19= 0
        ,price20= 0,price21= 0,price22= 0,price23= 0,price24= 0;
        if(jRadioButton1.isSelected())
{
    jTextField1.setEnabled(true);
item1="Aloo WcBurger,";
qty1=Integer.parseInt(jTextField1.getText());
price1=(qty1*30);
}
        
if(jRadioButton2.isSelected())
{
    jTextField3.setEnabled(true);
item2="WcVEGGIE,";
qty2=Integer.parseInt(jTextField3.getText());
price2=(qty2*60);
}

if(jRadioButton3.isSelected())
{
    jTextField4.setEnabled(true);
item3="Maharaja Wac,";
qty3=Integer.parseInt(jTextField4.getText());
price3=(qty3*85);
}

if(jRadioButton4.isSelected())
{
    jTextField5.setEnabled(true);
item4="Spicy Paneer WcBurger,";
qty4=Integer.parseInt(jTextField5.getText());
price4=(qty4*110);
}

if(jRadioButton5.isSelected())
{
    jTextField6.setEnabled(true);
item5="Spicy Paneer Wrap,";
qty5=Integer.parseInt(jTextField6.getText());
price5=(qty5*90);
}

if(jRadioButton6.isSelected())
{
    jTextField7.setEnabled(true);
item6="Aloo Wrap,";
qty6=Integer.parseInt(jTextField7.getText());
price6=(qty6*75);
}

if(jRadioButton7.isSelected())
{
    jTextField8.setEnabled(true);
item7="Chicken WcBurger,";
qty7=Integer.parseInt(jTextField8.getText());
price7=(qty7*45);
}

if(jRadioButton8.isSelected())
{
    jTextField9.setEnabled(true);
item8="Grilled Chicken WcBurger,";
qty8=Integer.parseInt(jTextField9.getText());
price8=(qty8*65);
}

if(jRadioButton9.isSelected())
{
    jTextField10.setEnabled(true);
item9="Maharaja Wac,";
qty9=Integer.parseInt(jTextField10.getText());
price9=(qty9*90);
}

if(jRadioButton10.isSelected())
{
    jTextField11.setEnabled(true);
item10="Spicy Chicken WcBurger,";
qty10=Integer.parseInt(jTextField11.getText());
price10=(qty10*120);
}

if(jRadioButton11.isSelected())
{
    jTextField12.setEnabled(true);
item11="Chicken Wrap,";
qty11=Integer.parseInt(jTextField12.getText());
price11=(qty11*85);
}

if(jRadioButton12.isSelected())
{
    jTextField13.setEnabled(true);
item12="Mutton Wrap,";
qty12=Integer.parseInt(jTextField13.getText());
price12=(qty12*100);
}

if(jRadioButton13.isSelected())
{
    jTextField14.setEnabled(true);
item13="WcPuff,";
qty13=Integer.parseInt(jTextField14.getText());
price13=(qty13*25);
}

if(jRadioButton14.isSelected())
{
    jTextField15.setEnabled(true);
item14="Chicken Nuggets,";
qty14=Integer.parseInt(jTextField15.getText());
price14=(qty14*55);
}

if(jRadioButton15.isSelected())
{
    jTextField16.setEnabled(true);
item15="Chicken Popcorn,";
qty15=Integer.parseInt(jTextField16.getText());
price15=(qty15*60);
}

if(jRadioButton16.isSelected())
{
    jTextField17.setEnabled(true);
item16="French Fries,";
qty16=Integer.parseInt(jTextField17.getText());
price16=(qty16*70);
}

if(jRadioButton17.isSelected())
{
    jTextField18.setEnabled(true);
item17="Chicken French Fries,";
qty17=Integer.parseInt(jTextField18.getText());
price17=(qty17*80);
}

if(jRadioButton18.isSelected())
{
    jTextField19.setEnabled(true);
item18="Veg Grilled Sandwich,";
qty18=Integer.parseInt(jTextField19.getText());
price18=(qty18*60);
}

if(jRadioButton19.isSelected())
{
    jTextField20.setEnabled(true);
item19="Ice Tea,";
qty19=Integer.parseInt(jTextField20.getText());
price19=(qty19*35);
}

if(jRadioButton20.isSelected())
{
    jTextField21.setEnabled(true);
item20="Black Tea,";
qty20=Integer.parseInt(jTextField21.getText());
price20=(qty20*40);
}

if(jRadioButton21.isSelected())
{
    jTextField22.setEnabled(true);
item21="Cold Coffee,";
qty21=Integer.parseInt(jTextField22.getText());
price21=(qty21*50);
}

if(jRadioButton22.isSelected())
{
    jTextField23.setEnabled(true);
item22="Hot Tea,";
qty22=Integer.parseInt(jTextField23.getText());
price22=(qty22*40);
}

if(jRadioButton23.isSelected())
{
    jTextField24.setEnabled(true);
item23="Drinking Water,";
qty23=Integer.parseInt(jTextField24.getText());
price23=(qty23*30);
}

if(jRadioButton24.isSelected())
{
    jTextField25.setEnabled(true);
item24="Coke/Fanta/Sprite";
qty24=Integer.parseInt(jTextField25.getText());
price24=(qty24*50);
}

try
    {
        Class.forName("java.sql.DriverManager");
        Connection con = (Connection)
        DriverManager.getConnection("jdbc:mysql://localhost/practical12","root","");
        Statement stmt = (Statement)
        con.createStatement();
        Statement stmt2= (Statement)
        con.createStatement();
       String username="select username from user1" ;
       ResultSet ar=stmt.executeQuery(username);
        if(ar.next())
        {
            user=ar.getString("username");
        }
       String query="select MAX(Ord_Id) from Order_det";
        ResultSet rs=stmt.executeQuery(query);
        
        if(rs.next());
        {
            indicate =rs.getString("MAX(Ord_Id)");
        }
        int a=Integer.parseInt(indicate)+1;

       String query1="insert into Order_det values('"+a+"','"+item1+"',"+qty1+","+price1+");";
       String query2="insert into Order_det values('"+a+"','"+item2+"',"+qty2+","+price2+");";
       String query3="insert into Order_det values('"+a+"','"+item3+"',"+qty3+","+price3+");";
       String query4="insert into Order_det values('"+a+"','"+item4+"',"+qty4+","+price4+");";
       String query5="insert into Order_det values('"+a+"','"+item5+"',"+qty5+","+price5+");";
       String query6="insert into Order_det values('"+a+"','"+item6+"',"+qty6+","+price6+");";
       String query7="insert into Order_det values('"+a+"','"+item7+"',"+qty7+","+price7+");";
       String query8="insert into Order_det values('"+a+"','"+item8+"',"+qty8+","+price8+");";
       String query9="insert into Order_det values('"+a+"','"+item9+"',"+qty9+","+price9+");";
       String query10="insert into Order_det values('"+a+"','"+item10+"',"+qty10+","+price10+");";
       String query11="insert into Order_det values('"+a+"','"+item11+"',"+qty11+","+price11+");";
       String query12="insert into Order_det values('"+a+"','"+item12+"',"+qty12+","+price12+");";
       String query13="insert into Order_det values('"+a+"','"+item13+"',"+qty13+","+price13+");";
       String query14="insert into Order_det values('"+a+"','"+item14+"',"+qty14+","+price14+");";
       String query15="insert into Order_det values('"+a+"','"+item15+"',"+qty15+","+price15+");";
       String query16="insert into Order_det values('"+a+"','"+item16+"',"+qty16+","+price16+");";
       String query17="insert into Order_det values('"+a+"','"+item17+"',"+qty17+","+price17+");";
       String query18="insert into Order_det values('"+a+"','"+item18+"',"+qty18+","+price18+");";
       String query19="insert into Order_det values('"+a+"','"+item19+"',"+qty19+","+price19+");";
       String query20="insert into Order_det values('"+a+"','"+item20+"',"+qty20+","+price20+");";
       String query21="insert into Order_det values('"+a+"','"+item21+"',"+qty21+","+price21+");";
       String query22="insert into Order_det values('"+a+"','"+item22+"',"+qty22+","+price22+");";
       String query23="insert into Order_det values('"+a+"','"+item23+"',"+qty23+","+price23+");";
       String query24="insert into Order_det values('"+a+"','"+item24+"',"+qty24+","+price24+");";
      
       String query25="insert into order_temp values('"+a+"');";
      
       String query26="update user3 set ord_id="+a+" where user='"+user+"';";
 
       
if(jRadioButton1.isSelected())
    stmt.executeUpdate(query1);
if(jRadioButton2.isSelected())
    stmt.executeUpdate(query2);
if(jRadioButton3.isSelected())
    stmt.executeUpdate(query3);
if(jRadioButton4.isSelected())
    stmt.executeUpdate(query4);
if(jRadioButton5.isSelected())
    stmt.executeUpdate(query5);
if(jRadioButton6.isSelected())
    stmt.executeUpdate(query6);
if(jRadioButton7.isSelected())
    stmt.executeUpdate(query7);
if(jRadioButton8.isSelected())
    stmt.executeUpdate(query8);
if(jRadioButton9.isSelected())
    stmt.executeUpdate(query9);
if(jRadioButton10.isSelected())
    stmt.executeUpdate(query10);
if(jRadioButton11.isSelected())
    stmt.executeUpdate(query11);
if(jRadioButton12.isSelected())
    stmt.executeUpdate(query12);
if(jRadioButton13.isSelected())
    stmt.executeUpdate(query13);
if(jRadioButton14.isSelected())
    stmt.executeUpdate(query14);
if(jRadioButton15.isSelected())
    stmt.executeUpdate(query15);
if(jRadioButton16.isSelected())
    stmt.executeUpdate(query16);
if(jRadioButton17.isSelected())
    stmt.executeUpdate(query17);
if(jRadioButton18.isSelected())
    stmt.executeUpdate(query18);
if(jRadioButton19.isSelected())
    stmt.executeUpdate(query19);
if(jRadioButton20.isSelected())
    stmt.executeUpdate(query20);
if(jRadioButton21.isSelected())
    stmt.executeUpdate(query21);
if(jRadioButton22.isSelected())
    stmt.executeUpdate(query22);
if(jRadioButton23.isSelected())
    stmt.executeUpdate(query23);
if(jRadioButton24.isSelected())
    stmt.executeUpdate(query24);
stmt2.executeUpdate(query25);
stmt.executeUpdate(query26);
    }

catch(Exception e)
{
    JOptionPane.showMessageDialog(this, e.getMessage());
}
this.setVisible(false);
new cart().setVisible(true);











// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
  if(jRadioButton1.isSelected())
{
    jTextField1.setEnabled(true);
}     
  else
{
    jTextField1.setEnabled(false);
}    // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
if(jRadioButton2.isSelected())
{
    jTextField3.setEnabled(true);
}     
  else
{
    jTextField3.setEnabled(false);  }      // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
if(jRadioButton3.isSelected())
{
    jTextField4.setEnabled(true);
}     
  else
{
    jTextField4.setEnabled(false);   }     // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
if(jRadioButton4.isSelected())
{
    jTextField5.setEnabled(true);
}     
  else
{
    jTextField5.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
if(jRadioButton5.isSelected())
{
    jTextField6.setEnabled(true);
}     
  else
{
    jTextField6.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
if(jRadioButton6.isSelected())
{
    jTextField7.setEnabled(true);
}     
  else
{
    jTextField7.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
if(jRadioButton7.isSelected())
{
    jTextField8.setEnabled(true);
}     
  else
{
    jTextField8.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
if(jRadioButton8.isSelected())
{
    jTextField9.setEnabled(true);
}     
  else
{
    jTextField9.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
if(jRadioButton9.isSelected())
{
    jTextField10.setEnabled(true);
}     
  else
{
    jTextField10.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
if(jRadioButton10.isSelected())
{
    jTextField11.setEnabled(true);
}     
  else
{
    jTextField11.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
if(jRadioButton11.isSelected())
{
    jTextField12.setEnabled(true);
}     
  else
{
    jTextField12.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
if(jRadioButton12.isSelected())
{
    jTextField13.setEnabled(true);
}     
  else
{
    jTextField13.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
if(jRadioButton13.isSelected())
{
    jTextField14.setEnabled(true);
}     
  else
{
    jTextField14.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
if(jRadioButton14.isSelected())
{
    jTextField15.setEnabled(true);
}     
  else
{
    jTextField15.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
   if(jRadioButton15.isSelected())
{
    jTextField16.setEnabled(true);
}     
  else
{
    jTextField16.setEnabled(false);   }       // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
if(jRadioButton16.isSelected())
{
    jTextField17.setEnabled(true);
}     
  else
{
    jTextField17.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
if(jRadioButton17.isSelected())
{
    jTextField18.setEnabled(true);
}     
  else
{
    jTextField18.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
if(jRadioButton18.isSelected())
{
    jTextField19.setEnabled(true);
}     
  else
{
    jTextField19.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
if(jRadioButton19.isSelected())
{
    jTextField20.setEnabled(true);
}     
  else
{
    jTextField20.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
if(jRadioButton20.isSelected())
{
    jTextField21.setEnabled(true);
}     
  else
{
    jTextField21.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
if(jRadioButton21.isSelected())
{
    jTextField22.setEnabled(true);
}     
  else
{
    jTextField22.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
if(jRadioButton22.isSelected())
{
    jTextField23.setEnabled(true);
}     
  else
{
    jTextField23.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
if(jRadioButton23.isSelected())
{
    jTextField24.setEnabled(true);
}     
  else
{
    jTextField24.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
if(jRadioButton24.isSelected())
{
    jTextField25.setEnabled(true);
}     
  else
{
    jTextField25.setEnabled(false);   }          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
jRadioButton1.setSelected(false);
jRadioButton2.setSelected(false);
jRadioButton3.setSelected(false);
jRadioButton4.setSelected(false);
jRadioButton5.setSelected(false);
jRadioButton6.setSelected(false);
jRadioButton7.setSelected(false);
jRadioButton8.setSelected(false);
jRadioButton9.setSelected(false);
jRadioButton10.setSelected(false);
jRadioButton11.setSelected(false);
jRadioButton12.setSelected(false);
jRadioButton13.setSelected(false);
jRadioButton14.setSelected(false);
jRadioButton15.setSelected(false);
jRadioButton16.setSelected(false);
jRadioButton17.setSelected(false);
jRadioButton18.setSelected(false);
jRadioButton19.setSelected(false);
jRadioButton20.setSelected(false);
jRadioButton21.setSelected(false);
jRadioButton22.setSelected(false);
jRadioButton23.setSelected(false);
jRadioButton24.setSelected(false);
jTextField1.setEnabled(false);
jTextField3.setEnabled(false);
jTextField4.setEnabled(false);
jTextField5.setEnabled(false);
jTextField6.setEnabled(false);
jTextField7.setEnabled(false);
jTextField8.setEnabled(false);
jTextField9.setEnabled(false);
jTextField10.setEnabled(false);
jTextField11.setEnabled(false);
jTextField12.setEnabled(false);
jTextField13.setEnabled(false);
jTextField14.setEnabled(false);
jTextField15.setEnabled(false);
jTextField16.setEnabled(false);
jTextField17.setEnabled(false);
jTextField18.setEnabled(false);
jTextField19.setEnabled(false);
jTextField20.setEnabled(false);
jTextField21.setEnabled(false);
jTextField22.setEnabled(false);
jTextField23.setEnabled(false);
jTextField24.setEnabled(false);
jTextField25.setEnabled(false);


// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
